// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @dev Generated by snarkjs (contracts/Verifier.sol) from the Vote circuit.
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[5] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @title Voting
 * @dev Anonymous voting secured by Groth16 zero-knowledge proofs.
 *
 * Each vote carries a proof that the sender knows the secret behind one leaf of
 * the registered voter Merkle tree, plus a nullifier derived from that secret
 * and the election ID. The proof is verified ON-CHAIN, so no relayer or
 * backend can add, alter or forge votes. Anyone may call castVote directly.
 *
 * The election moves through phases in one direction only:
 *   Registration -> RegistrationClosed -> Voting -> Ended
 * The voter Merkle root is set exactly once, when voting opens, so the owner
 * cannot add voters to the registry while votes are being cast.
 *
 * Public signals (fixed by the circuit):
 *   [0] root  [1] nullifierHash  [2] electionId  [3] candidateCount  [4] vote
 */
contract Voting {

    // ============ TYPES ============

    enum Phase { Registration, RegistrationClosed, Voting, Ended }

    // ============ CONSTANTS ============

    /// @dev BN254 scalar field; a root outside it could never match a proof.
    uint256 private constant SNARK_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // ============ STATE ============

    IGroth16Verifier public immutable verifier;
    address public owner;

    uint256 public immutable electionId;
    uint256 public immutable candidateCount;

    Phase public phase;

    /// @dev Root of the registered voter Merkle tree. 0 until voting opens,
    /// then fixed for the rest of the election.
    uint256 public merkleRoot;

    /// @dev candidate ID (1..candidateCount) => votes
    mapping(uint256 => uint256) public votes;
    uint256 public totalVotes;

    /// @dev nullifier => used
    mapping(bytes32 => bool) public nullifierUsed;

    // ============ EVENTS ============

    event VoteCast(uint256 indexed candidate, bytes32 indexed nullifier, uint256 timestamp);
    event RegistrationClosed(uint256 timestamp);
    event VotingOpened(uint256 merkleRoot, uint256 timestamp);
    event VotingEnded(uint256 timestamp);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    // ============ MODIFIERS ============

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner can call this");
        _;
    }

    // ============ CONSTRUCTOR ============

    constructor(
        address _verifier,
        uint256 _electionId,
        uint256 _candidateCount
    ) {
        require(_verifier != address(0), "Verifier address required");
        // The circuit range-checks candidateCount with 8 bits.
        require(_candidateCount >= 1 && _candidateCount <= 255, "Invalid candidate count");

        verifier = IGroth16Verifier(_verifier);
        electionId = _electionId;
        candidateCount = _candidateCount;
        owner = msg.sender;
        phase = Phase.Registration;
    }

    // ============ VOTING ============

    /**
     * @dev Cast a vote. Anyone may submit (typically the backend relayer), but
     * only a valid proof for the current root and election is accepted, and
     * the candidate is taken from the proof itself.
     */
    function castVote(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[5] calldata _pubSignals
    ) external {
        require(phase == Phase.Voting, "Voting is not open");
        require(_pubSignals[0] == merkleRoot, "Unknown Merkle root");
        require(_pubSignals[2] == electionId, "Wrong election");
        require(_pubSignals[3] == candidateCount, "Wrong candidate count");

        uint256 candidate = _pubSignals[4];
        require(candidate >= 1 && candidate <= candidateCount, "Invalid candidate ID");

        bytes32 nullifier = bytes32(_pubSignals[1]);
        require(!nullifierUsed[nullifier], "Duplicate vote: Nullifier already used");

        require(verifier.verifyProof(_pA, _pB, _pC, _pubSignals), "Invalid proof");

        nullifierUsed[nullifier] = true;
        votes[candidate]++;
        totalVotes++;

        emit VoteCast(candidate, nullifier, block.timestamp);
    }

    // ============ QUERIES ============

    function getVotes(uint256 _candidate) external view returns (uint256) {
        require(_candidate >= 1 && _candidate <= candidateCount, "Invalid candidate ID");
        return votes[_candidate];
    }

    function hasVoted(bytes32 _nullifier) external view returns (bool) {
        return nullifierUsed[_nullifier];
    }

    /// @return results votes per candidate; results[i] is candidate i + 1
    function getResults() external view returns (uint256[] memory results) {
        results = new uint256[](candidateCount);
        for (uint256 i = 0; i < candidateCount; i++) {
            results[i] = votes[i + 1];
        }
    }

    function getTotalVotes() external view returns (uint256) {
        return totalVotes;
    }

    // ============ ADMIN (one-way phase transitions) ============

    /// @dev Stops new registrations so the voter registry can be published
    /// and audited before voting opens.
    function closeRegistration() external onlyOwner {
        require(phase == Phase.Registration, "Registration is not open");
        phase = Phase.RegistrationClosed;
        emit RegistrationClosed(block.timestamp);
    }

    /// @dev Fixes the voter registry root and opens voting. Can happen once.
    function openVoting(uint256 _merkleRoot) external onlyOwner {
        require(phase == Phase.RegistrationClosed, "Close registration first");
        require(_merkleRoot != 0 && _merkleRoot < SNARK_FIELD, "Invalid Merkle root");
        merkleRoot = _merkleRoot;
        phase = Phase.Voting;
        emit VotingOpened(_merkleRoot, block.timestamp);
    }

    /// @dev Ends the election permanently.
    function endVoting() external onlyOwner {
        require(phase == Phase.Voting, "Voting is not open");
        phase = Phase.Ended;
        emit VotingEnded(block.timestamp);
    }

    function transferOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "New owner required");
        emit OwnershipTransferred(owner, _newOwner);
        owner = _newOwner;
    }
}
