/*
 * Compiles the Vote circuit, runs the Groth16 setup and exports every artifact
 * the rest of the system needs:
 *   build/main_js/main.wasm, build/vote_final.zkey, build/verification_key.json
 *   contracts/Verifier.sol           (on-chain Groth16 verifier)
 *   client/public/zk/vote.wasm|.zkey (browser proving)
 *
 * Powers of Tau: set PTAU_PATH to a ceremony file (e.g. Hermez
 * powersOfTau28_hez_final_14.ptau) for anything beyond local development.
 * Without it a single-contributor ptau is generated locally — NOT secure for
 * a real election.
 */
require("dotenv").config();

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execFileSync } = require("child_process");
const { PATHS, loadElectionConfig } = require("./lib/common");

const SNARKJS_CLI = path.join(PATHS.root, "node_modules/snarkjs/build/cli.cjs");

// circom 2.x: CIRCOM_PATH, else tools/circom(.exe), else `circom` on PATH.
function findCircom() {
  if (process.env.CIRCOM_PATH) {
    return process.env.CIRCOM_PATH;
  }
  const local = path.join(
    PATHS.root,
    "tools",
    process.platform === "win32" ? "circom.exe" : "circom"
  );
  return fs.existsSync(local) ? local : "circom";
}

function run(command, args) {
  execFileSync(command, args, { cwd: PATHS.root, stdio: "inherit" });
}

function snarkjs(...args) {
  run(process.execPath, [SNARKJS_CLI, ...args]);
}

function entropy() {
  return crypto.randomBytes(32).toString("hex");
}

function writeMainCircuit(depth) {
  const mainPath = path.join(PATHS.circuitsDir, "main.circom");
  fs.writeFileSync(
    mainPath,
    [
      "// GENERATED by scripts/buildCircuit.js from election.config.json — do not edit.",
      "pragma circom 2.0.0;",
      "",
      'include "Vote.circom";',
      "",
      "component main {public [root, nullifierHash, electionId, candidateCount, vote]} = " +
        `Vote(${depth});`,
      ""
    ].join("\n")
  );
  return mainPath;
}

function constraintCount(r1csPath) {
  const output = execFileSync(
    process.execPath,
    [SNARKJS_CLI, "r1cs", "info", r1csPath],
    { cwd: PATHS.root, encoding: "utf8" }
  );
  const match = output.match(/# of Constraints:\s*(\d+)/);
  if (!match) {
    throw new Error("Could not read constraint count from snarkjs r1cs info");
  }
  return Number(match[1]);
}

function ensurePtau(power) {
  if (process.env.PTAU_PATH) {
    if (!fs.existsSync(process.env.PTAU_PATH)) {
      throw new Error(`PTAU_PATH not found: ${process.env.PTAU_PATH}`);
    }
    return process.env.PTAU_PATH;
  }

  const ptauDir = path.join(PATHS.buildDir, "ptau");
  const finalPtau = path.join(ptauDir, `pot${power}_final.ptau`);

  if (fs.existsSync(finalPtau)) {
    return finalPtau;
  }

  console.warn(
    "\nWARNING: generating a local single-contributor Powers of Tau (2^" +
      power +
      ").\nThis is fine for development only. Set PTAU_PATH to a public ceremony file for real use.\n"
  );

  fs.mkdirSync(ptauDir, { recursive: true });
  const pot0 = path.join(ptauDir, `pot${power}_0000.ptau`);
  const pot1 = path.join(ptauDir, `pot${power}_0001.ptau`);

  snarkjs("powersoftau", "new", "bn128", String(power), pot0);
  snarkjs("powersoftau", "contribute", pot0, pot1, "--name=local-dev", `-e=${entropy()}`);
  snarkjs("powersoftau", "prepare", "phase2", pot1, finalPtau);

  fs.rmSync(pot0);
  fs.rmSync(pot1);
  return finalPtau;
}

function main() {
  const config = loadElectionConfig();
  fs.mkdirSync(PATHS.buildDir, { recursive: true });

  console.log(`\n[1/5] Compiling circuit (tree depth ${config.treeDepth})...`);
  writeMainCircuit(config.treeDepth);
  const circom = findCircom();
  try {
    run(circom, ["circuits/main.circom", "--r1cs", "--wasm", "--sym", "-o", "build"]);
  } catch (error) {
    if (error.code === "ENOENT") {
      throw new Error(
        "circom 2.x not found. Install it (https://docs.circom.io/getting-started/installation/), " +
          "place the binary in tools/, or set CIRCOM_PATH."
      );
    }
    throw error;
  }

  const r1cs = path.join(PATHS.buildDir, "main.r1cs");
  const constraints = constraintCount(r1cs);
  // Groth16 needs 2^power > constraints + public inputs; keep headroom.
  const power = Math.max(12, Math.ceil(Math.log2(constraints + 64)) + 1);
  console.log(`Constraints: ${constraints} -> Powers of Tau 2^${power}`);

  console.log("\n[2/5] Preparing Powers of Tau...");
  const ptau = ensurePtau(power);

  console.log("\n[3/5] Groth16 setup...");
  const zkey0 = path.join(PATHS.buildDir, "vote_0000.zkey");
  snarkjs("groth16", "setup", r1cs, ptau, zkey0);
  snarkjs("zkey", "contribute", zkey0, PATHS.zkey, "--name=local-dev", `-e=${entropy()}`);
  fs.rmSync(zkey0);

  console.log("\n[4/5] Exporting verification key and Solidity verifier...");
  snarkjs("zkey", "export", "verificationkey", PATHS.zkey, PATHS.vkey);
  const verifierPath = path.join(PATHS.root, "contracts/Verifier.sol");
  snarkjs("zkey", "export", "solidityverifier", PATHS.zkey, verifierPath);

  console.log("\n[5/5] Copying proving artifacts to the client...");
  fs.mkdirSync(PATHS.clientZkDir, { recursive: true });
  fs.copyFileSync(PATHS.wasm, path.join(PATHS.clientZkDir, "vote.wasm"));
  fs.copyFileSync(PATHS.zkey, path.join(PATHS.clientZkDir, "vote_final.zkey"));

  console.log("\nCircuit build complete.");
  console.log("Next: npm run tree:build && npm run compile");
}

main();
